from __future__ import annotations

import hashlib
import io
import json
import os
import tarfile
from pathlib import Path

import numpy as np
import pytest

from foldjax.models.protenix.data.search import (
    HttpResponse,
    LocalMsaClient,
    MsaPayload,
    MsaSearchPipeline,
    RemoteMMseqs2Client,
    SearchError,
    load_template_search_artifact,
)
from foldjax.models.protenix.data.search.msa import (
    LocalRnaMsaClient,
    RnaMsaPayload,
    RnaMsaSearchPipeline,
    apply_rna_msa_paths,
)
from foldjax.models.protenix.data.search.templates import (
    LocalTemplateSearchClient,
    TemplateSearchPipeline,
    apply_template_paths,
    resolve_template_search_hits,
)
from foldjax.models.protenix.data.template_features import _single_json_template

_PROTEIN_1TO3 = {
    "A": "ALA",
    "C": "CYS",
    "D": "ASP",
    "E": "GLU",
    "F": "PHE",
    "G": "GLY",
    "H": "HIS",
    "I": "ILE",
    "K": "LYS",
    "L": "LEU",
    "M": "MET",
    "N": "ASN",
    "P": "PRO",
    "Q": "GLN",
    "R": "ARG",
    "S": "SER",
    "T": "THR",
    "V": "VAL",
    "W": "TRP",
    "Y": "TYR",
}


def _write_fake_kalign(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, *, version: str = "3.3.5"
) -> Path:
    binary = tmp_path / f"kalign-{version}"
    binary.write_text(
        "#!/usr/bin/env python3\n"
        "import pathlib\n"
        "import sys\n"
        "if '--version' in sys.argv:\n"
        f"    print('kalign {version}')\n"
        "    raise SystemExit(0)\n"
        "input_path = pathlib.Path(sys.argv[sys.argv.index('-i') + 1])\n"
        "output_path = pathlib.Path(sys.argv[sys.argv.index('-o') + 1])\n"
        "output_path.write_text(input_path.read_text())\n"
    )
    binary.chmod(0o755)
    monkeypatch.setenv("PROTENIX_KALIGN_BINARY", str(binary))
    return binary


def _write_seqres_mmcif(path: Path, *, chain_id: str, sequence: str) -> None:
    rows = "\n".join(
        f"1 {index} {_PROTEIN_1TO3[residue]}"
        for index, residue in enumerate(sequence, start=1)
    )
    path.write_text(
        f"data_{path.stem}\n"
        "loop_\n"
        "_entity_poly_seq.entity_id\n"
        "_entity_poly_seq.num\n"
        "_entity_poly_seq.mon_id\n"
        f"{rows}\n"
        "loop_\n"
        "_struct_asym.id\n"
        "_struct_asym.entity_id\n"
        "A 1\n"
        "loop_\n"
        "_atom_site.label_asym_id\n"
        "_atom_site.auth_asym_id\n"
        "_atom_site.pdbx_PDB_model_num\n"
        f"A {chain_id} 1\n"
    )


class RecordingBackend:
    name = "fake"
    version = "db-2026-01"

    def __init__(self, payload: MsaPayload) -> None:
        self.payload = payload
        self.calls: list[str] = []

    def search(self, sequence: str) -> MsaPayload:
        self.calls.append(sequence)
        return self.payload


class RecordingRnaBackend:
    name = "fake-rna"
    version = "rna-db-2026"

    def __init__(self) -> None:
        self.calls: list[str] = []

    def search(self, sequence: str) -> RnaMsaPayload:
        self.calls.append(sequence)
        return RnaMsaPayload(
            unpaired=f">query\n{sequence}\n>hit\n{sequence[:-1]}-\n",
            source={"databases": ["rfam", "rnacentral", "nt-rna"]},
        )


def test_msa_pipeline_writes_paths_provenance_and_reuses_cache(tmp_path: Path) -> None:
    backend = RecordingBackend(
        MsaPayload(
            paired=">query\nACDE\n>paired\nACDE\n",
            unpaired=">query\nACDE\n>hit\nAC-E\n",
            source={"job_id": "job-7", "database": "uniref30-2026-01"},
        )
    )
    pipeline = MsaSearchPipeline(tmp_path, backend, options={"mode": "complete"})

    first = pipeline.search(["acde", "ACDE"])
    second = pipeline.search(["ACDE"])

    assert backend.calls == ["ACDE"]
    assert first[0] == first[1] == second[0]
    assert first[0]["pairedMsaPath"].endswith("/pairing.a3m")
    assert first[0]["unpairedMsaPath"].endswith("/non_pairing.a3m")
    provenance = json.loads(Path(first[0]["provenancePath"]).read_text())
    assert provenance["sequence_sha256"] != provenance["cache_key"]
    assert provenance["backend"] == {"name": "fake", "version": "db-2026-01"}
    assert provenance["options"] == {"mode": "complete"}
    assert provenance["source"]["job_id"] == "job-7"
    assert provenance["files"]["pairing.a3m"]["sha256"]


# Mapping digests and combined aatype/atom-position/atom-mask digests were
# generated by pinned OpenDDE on these exact examples with Kalign 3.3.5.
@pytest.mark.parametrize(
    ("payload", "message"),
    [
        (MsaPayload(paired="", unpaired=">query\nACDE\n"), "paired MSA"),
        (MsaPayload(paired=">query\nAAAA\n", unpaired=">query\nACDE\n"), "query"),
    ],
)
def test_msa_pipeline_rejects_missing_or_mismatched_results(
    tmp_path: Path, payload: MsaPayload, message: str
) -> None:
    with pytest.raises(SearchError, match=message):
        MsaSearchPipeline(tmp_path, RecordingBackend(payload)).search(["ACDE"])


def test_msa_pipeline_cache_key_covers_backend_version_and_options(
    tmp_path: Path,
) -> None:
    payload = MsaPayload(paired=">query\nACDE\n", unpaired=">query\nACDE\n")
    one = MsaSearchPipeline(
        tmp_path, RecordingBackend(payload), options={"database": "v1"}
    ).search(["ACDE"])[0]
    two = MsaSearchPipeline(
        tmp_path, RecordingBackend(payload), options={"database": "v2"}
    ).search(["ACDE"])[0]

    assert Path(one["pairedMsaPath"]).parent != Path(two["pairedMsaPath"]).parent


def test_rna_msa_pipeline_caches_and_applies_only_to_rna(tmp_path: Path) -> None:
    backend = RecordingRnaBackend()
    pipeline = RnaMsaSearchPipeline(
        tmp_path / "rna-cache", backend, options={"mode": "nhmmer"}
    )
    inference = {
        "name": "rna",
        "sequences": [
            {"proteinChain": {"sequence": "ACDE"}},
            {"rnaSequence": {"sequence": "AGCU"}},
            {"rnaSequence": {"sequence": "AGCU"}},
        ],
    }
    first = apply_rna_msa_paths(inference, pipeline)
    second = apply_rna_msa_paths(inference, pipeline)
    assert backend.calls == ["AGCU"]
    assert "unpairedMsaPath" not in first["sequences"][0]["proteinChain"]
    paths = [item["rnaSequence"]["unpairedMsaPath"] for item in first["sequences"][1:]]
    assert paths[0] == paths[1]
    assert paths[0] == second["sequences"][1]["rnaSequence"]["unpairedMsaPath"]
    provenance = json.loads((Path(paths[0]).parent / "provenance.json").read_text())
    assert provenance["backend"] == {"name": "fake-rna", "version": "rna-db-2026"}
    assert provenance["files"]["rna_msa.a3m"]["sha256"]


def test_local_rna_msa_client_uses_real_wrapper_boundary() -> None:
    def runner(command: list[str], **_: object):
        output = Path(command[command.index("--output") + 1])
        (output / "rna_msa.a3m").write_text(">query\nAGCU\n>hit\nAG-U\n")
        return type("Completed", (), {"returncode": 0, "stdout": "", "stderr": ""})()

    payload = LocalRnaMsaClient(
        ["fake-nhmmer-wrapper"], version="rfam-14.9", runner=runner
    ).search("AGCU")
    assert payload.unpaired.startswith(">query\nAGCU")
    assert payload.source["version"] == "rfam-14.9"


def test_local_client_runner_boundary_and_missing_output() -> None:
    def runner(command: list[str], **_: object):
        output = Path(command[command.index("--output") + 1])
        (output / "pairing.a3m").write_text(">query\nACDE\n")
        (output / "non_pairing.a3m").write_text(">query\nACDE\n")
        return type("Completed", (), {"returncode": 0, "stdout": "", "stderr": ""})()

    payload = LocalMsaClient(
        ["fake-mmseqs-wrapper"], version="db-v1", runner=runner
    ).search("ACDE")
    assert payload.paired == ">query\nACDE\n"
    assert payload.source["version"] == "db-v1"

    def incomplete_runner(command: list[str], **_: object):
        del command
        return type("Completed", (), {"returncode": 0, "stdout": "", "stderr": ""})()

    with pytest.raises(SearchError, match="did not produce"):
        LocalMsaClient(
            ["fake-mmseqs-wrapper"], version="db-v1", runner=incomplete_runner
        ).search("ACDE")


def test_remote_client_auth_validation_and_header_boundary() -> None:
    with pytest.raises(ValueError, match="username and password"):
        RemoteMMseqs2Client("https://msa.invalid", version="api-v1", username="u")
    with pytest.raises(ValueError, match="mutually exclusive"):
        RemoteMMseqs2Client(
            "https://msa.invalid",
            version="api-v1",
            username="u",
            password="p",
            auth_headers={"X-Api-Key": "secret"},
        )

    client = RemoteMMseqs2Client(
        "https://msa.invalid",
        version="api-v1",
        auth_headers={"X-Api-Key": "secret"},
        transport=lambda *_: pytest.fail("constructor must not access the network"),
    )
    assert client.headers["X-Api-Key"] == "secret"


def test_remote_client_mock_transport_happy_path() -> None:
    def archive(files: dict[str, str]) -> bytes:
        buffer = io.BytesIO()
        with tarfile.open(fileobj=buffer, mode="w:gz") as output:
            for name, content in files.items():
                raw = content.encode()
                info = tarfile.TarInfo(name)
                info.size = len(raw)
                output.addfile(info, io.BytesIO(raw))
        return buffer.getvalue()

    unpaired = archive(
        {
            "uniref.a3m": ">101\nACDE\n>hit\nAC-E\n",
            "bfd.mgnify30.metaeuk30.smag30.a3m": ">101\nACDE\n",
        }
    )
    paired = archive({"pair.a3m": ">101\nACDE\n>pair\nACDE\n"})
    responses = iter(
        [
            HttpResponse(200, b'{"status":"COMPLETE","id":"u-1"}'),
            HttpResponse(200, unpaired),
            HttpResponse(200, b'{"status":"COMPLETE","id":"p-1"}'),
            HttpResponse(200, paired),
        ]
    )
    requests: list[tuple[str, str]] = []

    def transport(method: str, url: str, *_: object) -> HttpResponse:
        requests.append((method, url))
        return next(responses)

    payload = RemoteMMseqs2Client(
        "https://msa.invalid/api", version="api-v1", transport=transport
    ).search("ACDE")

    assert payload.source == {"paired_job_id": "p-1", "unpaired_job_id": "u-1"}
    assert payload.paired.startswith(">101\nACDE")
    assert requests == [
        ("POST", "https://msa.invalid/api/ticket/msa"),
        ("GET", "https://msa.invalid/api/result/download/u-1"),
        ("POST", "https://msa.invalid/api/ticket/pair"),
        ("GET", "https://msa.invalid/api/result/download/p-1"),
    ]


def test_template_a3m_is_converted_to_intermediate_hits(tmp_path: Path) -> None:
    artifact = tmp_path / "hmmsearch.a3m"
    artifact.write_text(
        ">query\nAC-DE\n>1abc_A mol:protein length:5 1-5 Example protein\nACx-DE\n"
    )

    intermediate = load_template_search_artifact(
        artifact, query_sequence="ACDE", output_path=tmp_path / "hits.json"
    )

    assert intermediate["format"] == "hmmsearch_a3m"
    assert intermediate["hits"][0]["name"] == "1abc_A"
    assert intermediate["hits"][0]["query_to_hit_mapping"] == {
        "0": 0,
        "1": 1,
        "2": 3,
        "3": 4,
    }
    assert json.loads((tmp_path / "hits.json").read_text()) == intermediate


def test_queryless_hmmsearch_a3m_reconstructs_full_query_columns(
    tmp_path: Path,
) -> None:
    artifact = tmp_path / "hmmsearch.a3m"
    artifact.write_text(
        ">1abc_A/33-36 mol:protein length:36 template\nA-CdE\n",
        encoding="utf-8",
    )

    intermediate = load_template_search_artifact(
        artifact,
        query_sequence="ACDE",
    )

    assert intermediate["hits"][0]["name"] == "1abc_A/33-36"
    assert intermediate["hits"][0]["query"] == "ACDE"
    assert intermediate["hits"][0]["query_to_hit_mapping"] == {
        "0": 32,
        "2": 33,
        "3": 35,
    }


def test_template_hhr_is_converted_to_intermediate_hits(tmp_path: Path) -> None:
    artifact = tmp_path / "search.hhr"
    artifact.write_text(
        "No 1\n"
        ">2xyz_B example\n"
        "Probab=99.0 E-value=1e-10 Score=80.0 Aligned_cols=4 "
        "Identities=50% Sum_probs=3.5\n"
        "Q query            1 AC-DE 4 (4)\n"
        "T 2xyz_B           5 ACGFE 9 (20)\n"
    )

    intermediate = load_template_search_artifact(artifact, query_sequence="ACDE")

    assert intermediate["format"] == "hhr"
    assert intermediate["hits"][0]["sum_probs"] == 3.5
    assert intermediate["hits"][0]["query_to_hit_mapping"] == {
        "0": 4,
        "1": 5,
        "2": 7,
        "3": 8,
    }


def test_template_artifact_invalid_or_missing_fails_explicitly(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        load_template_search_artifact(tmp_path / "missing.a3m", query_sequence="ACDE")
    bad = tmp_path / "bad.txt"
    bad.write_text("not a template search result")
    with pytest.raises(ValueError, match="supported template search artifacts"):
        load_template_search_artifact(bad, query_sequence="ACDE")


def test_template_resolution_honors_max_four_and_missing_coordinate_errors(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _write_fake_kalign(tmp_path, monkeypatch)
    database = tmp_path / "mmcif"
    database.mkdir()
    query = "ACDEFGHIKLMN"
    _write_seqres_mmcif(database / "1abc.cif", chain_id="A", sequence=query)
    release_dates = tmp_path / "release_dates.json"
    release_dates.write_text(
        json.dumps(
            {
                "1abc": {"release_date": "2020-01-01"},
                "9xyz": {"release_date": "2020-01-01"},
            }
        )
    )
    obsolete = tmp_path / "obsolete.json"
    obsolete.write_text("{}")
    artifact = tmp_path / "hits.a3m"
    artifact.write_text(
        f">query\n{query}\n"
        + "".join(
            f">1abc_A mol:protein 1-12 hit-{index}\n{residue * 12}\n"
            for index, residue in enumerate("RSTVW")
        )
    )
    resolved = resolve_template_search_hits(
        artifact,
        query_sequence=query,
        mmcif_dir=database,
        max_templates=8,
        release_dates_path=release_dates,
        obsolete_pdbs_path=obsolete,
    )
    assert len(resolved) == 4
    assert all(hit["chainId"] == "A" for hit in resolved)

    missing = tmp_path / "missing.a3m"
    missing.write_text(f">query\n{query}\n>9xyz_A mol:protein 1-12\n{'Y' * 12}\n")
    with pytest.raises(FileNotFoundError, match="9xyz"):
        resolve_template_search_hits(
            missing,
            query_sequence=query,
            mmcif_dir=database,
            release_dates_path=release_dates,
            obsolete_pdbs_path=obsolete,
        )


def test_template_resolution_requires_cutoff_metadata(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Neither JSON can be skipped, and both are looked for in the store.

    `FOLDJAX_HOME` is pinned at an empty directory on purpose: the fallback
    below is by existence, so on a machine that has run `foldjax weights fetch`
    these calls would read the fetched copies and the test would pass or fail on
    whose machine it ran.
    """
    monkeypatch.setenv("FOLDJAX_HOME", str(tmp_path / "empty-store"))
    database = tmp_path / "mmcif"
    database.mkdir()
    artifact = tmp_path / "hits.a3m"
    artifact.write_text(
        ">query\nACDEFGHIKLMN\n>1abc_A mol:protein 1-12 hit\nACDEFGHIKLMN\n"
    )
    monkeypatch.delenv("PROTENIX_TEMPLATE_RELEASE_DATES_FILE", raising=False)
    monkeypatch.delenv("PROTENIX_TEMPLATE_OBSOLETE_FILE", raising=False)

    with pytest.raises(ValueError, match="PROTENIX_TEMPLATE_RELEASE_DATES_FILE"):
        resolve_template_search_hits(
            artifact, query_sequence="ACDEFGHIKLMN", mmcif_dir=database
        )

    release_dates = tmp_path / "release_dates.json"
    release_dates.write_text(json.dumps({"1abc": {"release_date": "2020-01-01"}}))
    with pytest.raises(ValueError, match="PROTENIX_TEMPLATE_OBSOLETE_FILE"):
        resolve_template_search_hits(
            artifact,
            query_sequence="ACDEFGHIKLMN",
            mmcif_dir=database,
            release_dates_path=release_dates,
        )


def test_fetched_cutoff_metadata_is_found_without_being_configured(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`foldjax weights fetch` puts both JSONs in the store; that is enough.

    They are published by the same project as the CCD, land in the same shared
    `assets/`, and are read for the same reason, so demanding two environment
    variables on top of having fetched them was a trap rather than a policy.
    """
    from foldjax.models.protenix.data.search import templates as templates_module
    from foldjax.paths import assets_dir

    monkeypatch.setenv("FOLDJAX_HOME", str(tmp_path / "store"))
    monkeypatch.delenv("PROTENIX_TEMPLATE_RELEASE_DATES_FILE", raising=False)
    monkeypatch.delenv("PROTENIX_TEMPLATE_OBSOLETE_FILE", raising=False)
    assets_dir().mkdir(parents=True)
    release_dates = assets_dir() / "release_date_cache.json"
    release_dates.write_text(json.dumps({"1abc": {"release_date": "2020-01-01"}}))
    obsolete = assets_dir() / "obsolete_to_successor.json"
    obsolete.write_text("{}")

    resolved = templates_module._metadata_path(
        None,
        environment="PROTENIX_TEMPLATE_RELEASE_DATES_FILE",
        label="release-date",
        managed="release_date_cache.json",
    )
    assert resolved == release_dates

    # And the whole call gets past both, whatever it decides about the hit.
    database = tmp_path / "mmcif"
    database.mkdir()
    query = "ACDEFGHIKLMN"
    _write_seqres_mmcif(database / "1abc.cif", chain_id="A", sequence=query)
    artifact = tmp_path / "hits.a3m"
    artifact.write_text(f">query\n{query}\n>1abc_A mol:protein 1-12 hit\n{query}\n")
    try:
        resolve_template_search_hits(artifact, query_sequence=query, mmcif_dir=database)
    except (ValueError, RuntimeError, FileNotFoundError) as error:
        assert "PROTENIX_TEMPLATE" not in str(error), error


def test_template_resolution_requires_explicit_kalign_binary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    database = tmp_path / "mmcif"
    database.mkdir()
    query = "ACDEFGHIKLMN"
    _write_seqres_mmcif(database / "1abc.cif", chain_id="A", sequence=query)
    artifact = tmp_path / "hits.a3m"
    artifact.write_text(
        f">query\n{query}\n>1abc_A mol:protein 1-12 hit\n{'Y' * len(query)}\n"
    )
    release_dates = tmp_path / "release_dates.json"
    release_dates.write_text(json.dumps({"1abc": {"release_date": "2020-01-01"}}))
    obsolete = tmp_path / "obsolete.json"
    obsolete.write_text("{}")
    monkeypatch.delenv("PROTENIX_KALIGN_BINARY", raising=False)
    monkeypatch.setenv("PATH", "")

    with pytest.raises(ValueError, match="PROTENIX_KALIGN_BINARY"):
        resolve_template_search_hits(
            artifact,
            query_sequence=query,
            mmcif_dir=database,
            release_dates_path=release_dates,
            obsolete_pdbs_path=obsolete,
        )
    with pytest.raises(FileNotFoundError, match="not executable"):
        resolve_template_search_hits(
            artifact,
            query_sequence=query,
            mmcif_dir=database,
            release_dates_path=release_dates,
            obsolete_pdbs_path=obsolete,
            kalign_binary=tmp_path / "missing-kalign",
        )


def test_template_resolution_rejects_a_kalign_below_the_floor(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Newer is allowed now; older is still refused.

    This asserted that 3.6.0 was rejected, which was the exact pin talking. The
    floor is what protects the alignment, and PyPI's wheel starts at 3.4.8, so
    an exact pin only made templates unreachable without a system package.
    """
    binary = _write_fake_kalign(tmp_path, monkeypatch, version="3.3.4")
    database = tmp_path / "mmcif"
    database.mkdir()
    query = "ACDEFGHIKLMN"
    _write_seqres_mmcif(database / "1abc.cif", chain_id="A", sequence=query)
    artifact = tmp_path / "hits.a3m"
    artifact.write_text(
        f">query\n{query}\n>1abc_A mol:protein 1-12 hit\n{'Y' * len(query)}\n"
    )
    release_dates = tmp_path / "release_dates.json"
    release_dates.write_text(json.dumps({"1abc": {"release_date": "2020-01-01"}}))
    obsolete = tmp_path / "obsolete.json"
    obsolete.write_text("{}")

    with pytest.raises(RuntimeError, match=r"requires Kalign 3\.3\.5.*3\.3\.4"):
        resolve_template_search_hits(
            artifact,
            query_sequence=query,
            mmcif_dir=database,
            release_dates_path=release_dates,
            obsolete_pdbs_path=obsolete,
            kalign_binary=binary,
        )


def _hhr_hit(
    index: int,
    name: str,
    hit_sequence: str,
    sum_probs: float,
    *,
    aligned_cols: int | None = None,
) -> str:
    query = "ACDEFGHIKLMNPQRSTVWY"[: len(hit_sequence)]
    cols = len(hit_sequence) if aligned_cols is None else aligned_cols
    return (
        f"No {index}\n"
        f">{name} synthetic\n"
        f"Probab=99.0 Aligned_cols={cols} Sum_probs={sum_probs}\n"
        f"Q query            1 {query} {len(query)} ({len(query)})\n"
        f"T {name:<16} 1 {hit_sequence} {len(hit_sequence)} "
        f"({len(hit_sequence)})\n"
    )


def test_template_resolution_matches_opendde_prefilter_order_and_dedup(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _write_fake_kalign(tmp_path, monkeypatch)
    query = "ACDEFGHIKLMNPQRSTVWY"
    artifact = tmp_path / "hits.hhr"
    artifact.write_text(
        "".join(
            [
                _hhr_hit(1, "1mis_A", "GGGGGGGGGGGG", 10.0),
                _hhr_hit(2, "1aaa_A", "AAAAAAAAAAAA", 1.0),
                _hhr_hit(3, "2bbb_B.1", "AAAAAAAAAAAA", 9.0),
                _hhr_hit(4, "3ccc_A", "CCCCCCCCCCCC", 8.0),
                _hhr_hit(5, "4old_C", "DDDDDDDDDDDD", 7.0),
                _hhr_hit(6, "6unk_A", "EEEEEEEEEEEE", 6.0),
                _hhr_hit(7, "7dup_A", query, 5.0),
                _hhr_hit(8, "8sho_A", "FFFFFFFFF", 4.0),
                _hhr_hit(9, "9low_A", "HHHHHHHHHHHH", 3.0, aligned_cols=2),
                _hhr_hit(10, "2ddd_D", "IIIIIIIIIIII", 2.0),
                _hhr_hit(11, "3eee_E", "KKKKKKKKKKKK", 1.5),
                _hhr_hit(12, "4fff_F", "LLLLLLLLLLLL", 1.25),
            ]
        )
    )
    database = tmp_path / "mmcif"
    database.mkdir()
    for pdb_id, chain_id in {
        "1aaa": "A",
        "2bbb": "B.1",
        "5new": "C",
        "2ddd": "D",
        "3eee": "E",
        "4fff": "F",
    }.items():
        _write_seqres_mmcif(
            database / f"{pdb_id}.cif", chain_id=chain_id, sequence=query
        )
    release_dates = tmp_path / "release_dates.json"
    release_dates.write_text(
        json.dumps(
            {
                pdb_id: {"release_date": release_date}
                for pdb_id, release_date in {
                    "1mis": "2020-01-01",
                    "1aaa": "2020-01-01",
                    "2bbb": "2020-01-01",
                    "3ccc": "2021-10-01",
                    "4old": "2020-01-01",
                    "5new": "2021-09-30",
                    "7dup": "2020-01-01",
                    "8sho": "2020-01-01",
                    "9low": "2020-01-01",
                    "2ddd": "2020-01-01",
                    "3eee": "2020-01-01",
                    "4fff": "2020-01-01",
                }.items()
            }
        )
    )
    obsolete = tmp_path / "obsolete.json"
    obsolete.write_text(json.dumps({"4old": "5new"}))
    monkeypatch.setenv("PROTENIX_TEMPLATE_RELEASE_DATES_FILE", str(release_dates))
    monkeypatch.setenv("PROTENIX_TEMPLATE_OBSOLETE_FILE", str(obsolete))

    resolved = resolve_template_search_hits(
        artifact, query_sequence=query, mmcif_dir=database
    )

    assert [(hit["pdbId"], hit["chainId"]) for hit in resolved] == [
        ("2bbb", "B.1"),
        ("5new", "C"),
        ("2ddd", "D"),
        ("3eee", "E"),
    ]


@pytest.mark.parametrize(
    ("example_json", "artifact_path", "expected"),
    [
        (
            "example_9fm7.json",
            "9fm7/hmmsearch.a3m",
            [
                (
                    "5ocm",
                    "A",
                    "5a08463e330ab8580b546796834a0e479a16a15106645e90cb9b3d2378510887",
                    "74772ae4217f19b21b9854e19debae44896e38bc2875f1f0b1bd5c96e72bc638",
                ),
                (
                    "3zgy",
                    "A",
                    "4b38fb72846e48eb35d7fc4ab2144939cd6c447a711ca4131ce174bdbad68544",
                    "9f3c8846d5e6db575f96b791e0bdb5908c712780c71688a55dbaa3a551e0413b",
                ),
                (
                    "5a9s",
                    "B",
                    "deb8ab5bfcea5083df1e0e84f0275adfaafe4f40a8c1708998fdc0f1b0869d63",
                    "0e79a791d06c94067ecd1caa1bd8b229924e025e3a12eab5f028283fce844947",
                ),
                (
                    "5a9r",
                    "A",
                    "deb8ab5bfcea5083df1e0e84f0275adfaafe4f40a8c1708998fdc0f1b0869d63",
                    "a918e3d4cb2c2045907372d244e48e17a9e26245aff21463e54a0ee50565dfc5",
                ),
            ],
        ),
        (
            "example_mgyp004658859411.json",
            "MGYP004658859411/concat.hhr",
            [
                (
                    "2pe5",
                    "B",
                    "5e16352570a290cdd9fda2873622d9f1722dd4eca5450d5e7503d5b2e0cf6f2e",
                    "89505597d9654fe40d682c02feee3710fb469bb611edf2127e9943550e523cfa",
                ),
                (
                    "3kjx",
                    "D",
                    "ae118976e84e1b299670fb94f232229851aec69bdc0ab30bfd684ff10dce25e5",
                    "8866b7c148b83f1e88a4d452faf782f31bb90deec866e212305c3d25c59190d5",
                ),
                (
                    "1jft",
                    "A",
                    "665dc9548c79f53531af7e48032ca7c1b939da559c271abc9425bdbb1d7702fb",
                    "8a2a9692603543489494720ee762121fb3261a592f8bc3fc07a1359dbc6c4827",
                ),
                (
                    "1qpz",
                    "A",
                    "665dc9548c79f53531af7e48032ca7c1b939da559c271abc9425bdbb1d7702fb",
                    "3395db8498a5c36770eb0f1e31b369bf33166c7618017322b1d16cdd945856f3",
                ),
            ],
        ),
    ],
)
def test_official_opendde_template_mappings_and_features_match_hashes(
    example_json: str,
    artifact_path: str,
    expected: list[tuple[str, str, str, str]],
) -> None:
    binary = os.environ.get("PROTENIX_KALIGN_BINARY")
    if binary is None:
        pytest.skip("set PROTENIX_KALIGN_BINARY to the pinned Kalign 3.3.5 binary")
    workspace = Path(__file__).resolve().parents[4]
    examples = workspace / "OpenDDE/examples/examples_with_template"
    database = workspace / "opendde_jax/weights/template_mmcif"
    release_dates = workspace / "protenix/common/release_date_cache.json"
    obsolete = workspace / "protenix/common/obsolete_to_successor.json"
    required = [examples / example_json, examples / artifact_path, database]
    if not all(path.exists() for path in [*required, release_dates, obsolete]):
        pytest.skip("official OpenDDE template examples/assets are unavailable")
    job = json.loads((examples / example_json).read_text())[0]
    query = job["sequences"][0]["proteinChain"]["sequence"]

    resolved = resolve_template_search_hits(
        examples / artifact_path,
        query_sequence=query,
        mmcif_dir=database,
        release_dates_path=release_dates,
        obsolete_pdbs_path=obsolete,
        kalign_binary=binary,
    )

    actual: list[tuple[str, str, str, str]] = []
    for template in resolved:
        mapping = dict(
            zip(
                template["queryIndices"],
                template["templateIndices"],
                strict=True,
            )
        )
        mapping_digest = hashlib.sha256(
            json.dumps(sorted(mapping.items()), separators=(",", ":")).encode()
        ).hexdigest()
        features = _single_json_template(template, len(query))
        feature_hasher = hashlib.sha256()
        feature_hasher.update(
            np.asarray(features["template_aatype"], dtype="<i4").tobytes()
        )
        feature_hasher.update(
            np.asarray(features["template_all_atom_positions"], dtype="<f4").tobytes()
        )
        feature_hasher.update(
            np.asarray(features["template_all_atom_masks"], dtype="<f4").tobytes()
        )
        actual.append(
            (
                template["pdbId"],
                template["chainId"],
                mapping_digest,
                feature_hasher.hexdigest(),
            )
        )
    assert actual == expected


def test_local_template_search_pipeline_caches_and_applies_paths(
    tmp_path: Path,
) -> None:
    calls = []

    def runner(command: list[str], **_: object):
        calls.append(command)
        output = Path(command[command.index("--output") + 1])
        (output / "templates.a3m").write_text(
            ">query\nACDEF\n>1abc_A mol:protein 1-5\nACDEF\n"
        )
        return type("Completed", (), {"returncode": 0, "stdout": "", "stderr": ""})()

    msa = tmp_path / "query.a3m"
    msa.write_text(">query\nACDEF\n")
    backend = LocalTemplateSearchClient(
        ["fake-template-wrapper"], version="pdb-2026", runner=runner
    )
    pipeline = TemplateSearchPipeline(tmp_path / "cache", backend)
    inference = {
        "sequences": [
            {"proteinChain": {"sequence": "ACDEF", "unpairedMsaPath": str(msa)}}
        ]
    }
    first = apply_template_paths(inference, pipeline)
    second = apply_template_paths(inference, pipeline)
    path = first["sequences"][0]["proteinChain"]["templatesPath"]
    assert path == second["sequences"][0]["proteinChain"]["templatesPath"]
    assert len(calls) == 1
    assert Path(path).name == "templates.a3m"
    provenance = json.loads((Path(path).parent / "provenance.json").read_text())
    assert provenance["backend"] == {"name": "local-template", "version": "pdb-2026"}


def test_template_search_requires_protein_msa_path(tmp_path: Path) -> None:
    backend = LocalTemplateSearchClient(
        ["unused"], version="v1", runner=lambda *_args, **_kwargs: None
    )
    pipeline = TemplateSearchPipeline(tmp_path / "cache", backend)
    with pytest.raises(SearchError, match="requires pairedMsaPath or unpairedMsaPath"):
        apply_template_paths(
            {"sequences": [{"proteinChain": {"sequence": "ACDEF"}}]}, pipeline
        )


def _write_banner_only_kalign(directory: Path, name: str, banner: str) -> Path:
    """A stand-in that answers --version and nothing else."""
    import sys

    binary = directory / name
    binary.write_text(
        f"#!{sys.executable}\n"
        f"print({banner!r})\n"
        "raise SystemExit(0)\n"
    )
    binary.chmod(0o755)
    return binary


def test_resolver_accepts_the_wheels_console_script(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`kalign-py` is the only Kalign installable without a system package.

    PyPI's `kalign-python` wheel installs under that name and prints a banner
    to match, so a resolver that looks for `kalign` alone reports a working
    aligner as missing -- which is what this environment did.
    """
    from foldjax.models.protenix.data.search import templates

    monkeypatch.delenv("PROTENIX_KALIGN_BINARY", raising=False)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    binary = _write_banner_only_kalign(bin_dir, "kalign-py", "kalign-py 3.6.0")
    monkeypatch.setenv("PATH", str(bin_dir))

    assert templates._resolve_kalign_binary(None) == str(binary)


def test_resolver_refuses_an_older_kalign_and_an_unreadable_banner(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The floor is a floor, and an unparsable banner is below it.

    Falling back to the whole banner text as the version used to pass an exact
    string comparison only by never matching; under an ordering it has to sort
    below every real version instead of raising a type error or slipping
    through.
    """
    from foldjax.models.protenix.data.search import templates

    monkeypatch.delenv("PROTENIX_KALIGN_BINARY", raising=False)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    monkeypatch.setenv("PATH", str(bin_dir))

    old = _write_banner_only_kalign(bin_dir, "kalign", "kalign 3.3.4")
    with pytest.raises(RuntimeError, match="3.3.5 or newer"):
        templates._resolve_kalign_binary(str(old))

    mute = _write_banner_only_kalign(bin_dir, "kalign-mute", "no version here")
    with pytest.raises(RuntimeError, match="3.3.5 or newer"):
        templates._resolve_kalign_binary(str(mute))


def test_resolver_accepts_the_version_the_pin_named(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from foldjax.models.protenix.data.search import templates

    monkeypatch.delenv("PROTENIX_KALIGN_BINARY", raising=False)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    monkeypatch.setenv("PATH", str(bin_dir))
    exact = _write_banner_only_kalign(bin_dir, "kalign", "kalign 3.3.5")

    assert templates._resolve_kalign_binary(str(exact)) == str(exact)
