"""The vendored chemistry tables, against the module they were generated from.

`chemistry.py` is generated by `scripts/generate_esmfold2_chemistry.py` reading
the installed upstream, so the risk is not transcription -- it is *staleness*:
a regenerated upstream, a stale committed file, and nothing to say so. This
re-derives every entry when upstream is installed and falls back to structural
checks when it is not, so the torch-free environment still tests something.
"""

from __future__ import annotations

import pytest

from foldjax.models.esmfold2.data import chemistry


def _upstream():
    return pytest.importorskip("transformers.models.esmfold2.protein_utils")


@pytest.mark.parametrize(
    "name",
    [
        "PROTEIN_1TO3",
        "PROTEIN_RESIDUE_TO_RES_TYPE",
        "ESM_PROTEIN_VOCAB",
        "PROTEIN_HEAVY_ATOMS",
        "PROTEIN_REF_POS",
        "PROTEIN_CHARGED_ATOMS",
    ],
)
def test_each_table_matches_upstream(name: str) -> None:
    assert getattr(chemistry, name) == getattr(_upstream(), name)


def test_the_scalars_and_element_map_match_upstream() -> None:
    upstream = _upstream()
    assert chemistry.MOL_TYPE_PROTEIN == upstream.MOL_TYPE_PROTEIN
    assert chemistry.PROTEIN_UNK_RES_TYPE == upstream.PROTEIN_UNK_RES_TYPE
    assert chemistry.MSA_GAP_TOKEN_ID == upstream.MSA_GAP_TOKEN_ID
    assert chemistry.PROTEIN_ELEMENT_TO_ATOMIC_NUM == (
        upstream._PROTEIN_ELEMENT_TO_ATOMIC_NUM
    )


def test_the_atom_name_encoding_matches_upstream() -> None:
    upstream = _upstream()
    for name in ("N", "CA", "CB", "OXT", "NE2", "CD1"):
        assert chemistry.encode_atom_name(name) == upstream._encode_atom_name(name)


def test_every_heavy_atom_has_a_reference_position() -> None:
    """Torch-free: a residue missing one would raise deep inside the featuriser."""
    for residue, names in chemistry.PROTEIN_HEAVY_ATOMS.items():
        positions = chemistry.PROTEIN_REF_POS[residue]
        missing = [name for name in names if name not in positions]
        assert not missing, f"{residue} is missing {missing}"
        assert "CA" in names, f"{residue} has no CA to fall back on"


def test_the_reverse_maps_are_consistent() -> None:
    """Torch-free: the two directions of the residue table must round-trip."""
    for letter, residue in chemistry.PROTEIN_1TO3.items():
        index = chemistry.PROTEIN_RESIDUE_TO_RES_TYPE.get(residue)
        if index is None:
            continue
        assert chemistry.RES_TYPE_TO_3LETTER[index] == residue
        # The letter map keeps the *first* letter that named a residue, so it
        # round-trips only when the residue has one name -- which every
        # standard one does.
        assert chemistry.RES_TYPE_TO_LETTER[index] == letter
