"""Backend interface."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from typing import Any

from foldjax import execution
from foldjax.schema import (
    ModelCapabilities,
    PredictionRequest,
    PredictionResult,
    _strict_integer,
)


class Backend(ABC):
    name: str

    #: Explicit opt-in to dispatcher-managed instance reuse.  The historical
    #: contract constructs a fresh backend for every scalar seed; keeping that
    #: default matters for third-party adapters whose instances are stateful.
    session_reuse: bool = False

    #: Backend-specific option names accepted in addition to the native names
    #: generated by ``sampling_options`` and ``execution_options``. ``None``
    #: preserves the open-ended contract for third-party backends; FoldJAX's
    #: built-ins all declare a set so ``plan`` can reject a typo before any
    #: output directory or model runtime is touched.
    native_options: frozenset[str] | None = None

    #: Option keys that change the compiled program. Only these participate in
    #: the cache namespace, so options that merely affect output formatting do
    #: not fragment the compilation cache.
    compile_options: tuple[str, ...] = ()

    #: Model-neutral sampling knob -> this backend's own option name. Every
    #: model calls "how many structures" something different, so the request
    #: carries one spelling and the adapter translates it.
    sampling_options: dict[str, str] = {}

    #: The same idea one level down, for the knobs that were left native:
    #: neutral knob -> (this backend's name, {neutral value: its value}).
    #: See `foldjax.execution` for the vocabulary and why `auto` never falls
    #: back silently.
    execution_options: dict[str, tuple[str, dict[str, str]]] = {}

    #: Dynamic shape axes understood by this backend's padding implementation.
    #: The public capability repeats this for discovery; this class attribute is
    #: the validation authority used before any model runtime is imported.
    padding_axes: tuple[str, ...] = ()

    def apply_sampling(self, request: PredictionRequest) -> dict[str, Any]:
        """Merge the request's sampling and execution knobs into native options.

        A knob the backend cannot express is an error, and so is setting both
        the neutral knob and its native spelling: silently preferring one would
        change how many structures come back without changing the exit code.
        """
        options = execution.translate(
            execution.normalize(
                dict(request.options),
                native={name for name, _ in self.execution_options.values()},
            ),
            self.execution_options,
            model=self.name,
        )
        for knob, value in request.sampling.items():
            native = self.sampling_options.get(knob)
            if native is None:
                raise ValueError(f"{self.name} does not support {knob}")
            if native in options:
                raise ValueError(
                    f"{knob} and the native option {native!r} were both set for "
                    f"{self.name}; pass one of them"
                )
            options[native] = value
        return options

    def validate_request(self, request: PredictionRequest) -> None:
        """Validate the cheap, side-effect-free part of a prediction request.

        This is shared by planning and execution. Runtime artifacts and model
        data remain prediction-time concerns, but an unsupported input dialect,
        neutral knob, execution value, or misspelled native option is knowable
        without loading weights and must have the same answer in both paths.
        """
        capabilities = self.capabilities()
        if request.input_format not in capabilities.input_formats:
            raise ValueError(
                f"{self.name} does not support input format {request.input_format!r}"
            )
        self._validate_representations(request, capabilities)
        options = self.apply_sampling(request)
        if request.padding is not None:
            if not self.padding_axes:
                raise ValueError(f"{self.name} does not support input padding")
            unsupported_padding = sorted(
                set(request.padding.explicit_axes) - set(self.padding_axes)
            )
            if unsupported_padding:
                raise ValueError(
                    f"{self.name} does not support explicit padding axes: "
                    f"{', '.join(unsupported_padding)}"
                )
        # Native spellings are an escape hatch, but they still mean the same
        # thing as the neutral fields.  Validate them with the public request's
        # exact integer contract so a string/float/bool cannot pass ``plan`` and
        # fail only after a model starts loading.
        for native in self.sampling_options.values():
            if native in options:
                _strict_integer(options[native], name=native, minimum=1)
        if self.native_options is None:
            return
        generated = set(self.sampling_options.values())
        generated.update(native for native, _values in self.execution_options.values())
        unsupported = sorted(set(options) - generated - set(self.native_options))
        if unsupported:
            raise ValueError(
                f"unsupported {self.name} options: {', '.join(unsupported)}"
            )
        self.validate_native_options(options)

    def _validate_representations(
        self,
        request: PredictionRequest,
        capabilities: ModelCapabilities,
    ) -> None:
        """Reject invalid representation selectors and unsupported fan-out.

        Native adapters resolve these names again when they decide which arrays
        to persist.  Planning must apply the same comma-separated/``all``
        vocabulary first, though: otherwise an invalid name is discovered only
        after weights and model-specific runtime state have started loading.
        The public result owns one representation archive, so one request also
        cannot capture representations from more than one seed without losing
        every handle but one.
        """
        if not request.representations:
            return
        available = capabilities.representations
        found = False
        selected_all = False
        for entry in request.representations:
            for part in str(entry).split(","):
                part = part.strip()
                if not part:
                    continue
                if part == "all":
                    if not available:
                        raise ValueError(
                            f"{self.name} does not expose trunk representations"
                        )
                    # This matches the native resolver: ``all`` selects the
                    # complete capability list and supersedes later entries.
                    found = True
                    selected_all = True
                    break
                if part not in available:
                    produced = ", ".join(available) or "none"
                    raise ValueError(
                        f"unknown representation {part!r} for {self.name}; "
                        f"this model produces: {produced}"
                    )
                found = True
            if selected_all:
                break
        if not found:
            raise ValueError(
                "representations must name at least one representation or 'all'"
            )
        if len(request.resolved_seeds) > 1:
            raise ValueError(
                "representations cannot be combined with multiple seeds: "
                "PredictionResult carries one representation archive; run one "
                "seed per request"
            )

    def validate_native_options(self, options: dict[str, Any]) -> None:
        """Validate built-in option values without importing a model runtime.

        Subclasses override this only for checks that are pure and cheap. The
        hook receives the translated native mapping so it can reuse the same
        helpers as ``predict`` while keeping planning free of preprocessing,
        checkpoint loading, compilation, downloads, and output writes.
        """

    @abstractmethod
    def capabilities(self) -> ModelCapabilities: ...

    @abstractmethod
    def predict(self, request: PredictionRequest) -> PredictionResult: ...

    @contextmanager
    def session(self, requests: Sequence[PredictionRequest]) -> Iterator[Backend]:
        """Keep request-scoped runtime state while executing related runs.

        Only backends with ``session_reuse = True`` are dispatched through
        this single-threaded context. Large built-ins may override it to load
        one checkpoint for several inputs or seeds. The context boundary is
        deliberate: FoldJAX must not turn multi-gigabyte model state into a
        process-global cache, retain two models while switching backends, or
        leak a failed run into the next request. Implementations must defer
        fallible loading to :meth:`predict`, where ``on_error`` applies, and
        make context cleanup non-throwing.
        """

        del requests
        yield self

    def invalidate_session(self) -> None:
        """Discard reusable state after an absorbed prediction failure.

        A backend that implements :meth:`session` may override this hook.  The
        no-op keeps third-party backends source-compatible while allowing the
        dispatcher to preserve the historical failure-isolation contract.
        """

    def observe_resumed(self, request: PredictionRequest) -> None:
        """Bind a reused artifact to request-scoped runtime state, if any."""

    def validate_session(self, request: PredictionRequest) -> None:
        """Refuse when resources used by this session changed on disk."""

    def cache_profile(self, request: PredictionRequest) -> dict[str, Any]:
        """Return the compile-relevant identity of ``request`` for this backend.

        Neutral sampling/execution knobs are translated first, so spelling the
        same schedule through ``num_steps`` or a backend's native ``steps``
        selects one namespace. JSON normalization happens in ``cache_namespace``.
        """
        options = self.apply_sampling(request)
        return {
            key: options[key]
            for key in self.compile_options
            if key in options
        }
